# Generated by Django 5.1.4 on 2024-12-11 21:37

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(default='products/asd.png', upload_to=products.models.upload_to, verbose_name='Image')),
                ('price', models.FloatField(default=100)),
                ('qte_stock', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
